version: "3.9"

services:

  chatwoot:
    image: chatwoot/chatwoot:latest
    env_file:
      - ../services/chatwoot/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks:
      - internal

  sidekiq:
    image: chatwoot/chatwoot:latest
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq
    env_file:
      - ../services/chatwoot/.env
    restart: always
    networks:
      - internal

  postgres:
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=Phillip
      - POSTGRES_PASSWORD=Growento2025!
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:
