version: "3.9"

services:

  chatwoot:
    image: chatwoot/chatwoot:latest
    env_file:
      - ../services/chatwoot/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - internal

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=easeEstateCW
      - POSTGRES_USER=Phillip
      - POSTGRES_PASSWORD=Growento2025!
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:

